spring:
  application:
    name: installment
  datasource:
    url: jdbc:postgresql://localhost:5432/installment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
secret:
  app:
    key: ${SECRET_KEY}
