spring:
  application:
    name: installment
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET_KEY}
  flyway:
    enabled: true
    baseline-on-migrate: true
secret:
  app:
    key: ${SECRET_KEY}
password:
  user:
    admin: ${PASSWORD_ADMIN}
springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: com.application.api.installment.controllers
